export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILED = "FETCH_POST_FAILED";
export const FETCH_POST_LOADING = "FETCH_POST_LOADING";

export const FETCH_MY_POST_LOADING = "FETCH_MY_POST_LOADING";
export const FETCH_MY_POST_SUCCESS = "FETCH_MY_POST_SUCCESS";
export const FETCH_MY_POST_FAILED = "FETCH_MY_POST_FAILED";

export const LIKE_POST = "LIKE_POST";
export const UNLIKE_POST = "UNLIKE_POST";

export const LIKE_POST_LOADING = "LIKE_POST_LOADING";
export const UNLIKE_POST_LOADING = "UNLIKE_POST_LOADING";

export const ADD_COMMENT = "ADD_COMMENT";

export const POST_DELETED = "POST_DELETED";

export const UPDATE_PIC = "UPDATE_PIC";