export const USER_PROFILE_LOADING = "USER_PROFILE_LOADING";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILED = "USER_PROFILE_FAILED";

export const USER_PROFILE_FOLLOWING = "USER_PROFILE_FOLLOWING";
export const USER_PROFILE_UNFOLLOWING = "USER_PROFILE_UNFOLLOWING";